### ISSUE TITLE
Ignore blank signs

### ISSUE THREAD

**Issue by DlljsCodes** [TechnicJelle/BlueMapSignExtractor#50]
Signs that are completely blank and have no text on them (e.g. signs used to block fluids and support paintings) should be ignored when extracted so they don't show up as redundant markers on the BlueMap

**Comment by TechnicJelle** [comment]
I am working on a feature that will allow you to filter signs #5.
This filtering feature will also allow you to filter out signs without any text on them.

**Comment by TechnicJelle** [comment]
Done in https://github.com/TechnicJelle/BlueMapSignExtractor/releases/tag/v1.4
