### ISSUE TITLE
Option in the config to not display empty signs

### ISSUE THREAD

**Issue by mikinol** [TechnicJelle/BlueMapSignExtractor#63]

**Comment by TechnicJelle** [comment]
I'm working on it...
But I've had so little time, and also I'm likely going to rethink the whole thing....
Duplicate of #50.

In the meantime, you could maybe use #38

**Comment by TechnicJelle** [comment]
Ah, I suppose I should merge that PR in the meantime...
I won't be able to add this feature in the better way that I wanted to do soon enough.

**Comment by TechnicJelle** [comment]
Done in https://github.com/TechnicJelle/BlueMapSignExtractor/releases/tag/v1.4
